[application]
# role: identifier for WindowManager (used in layers.json)
# e.g. role = "WebBrowser"
role = "HVAC"

# launch by "POSIX"(fork/exec), "AFM_DBUS"(afm via dbus),  "AFM_WEBSOCKET"(afm via websockt)
method = "POSIX"

# path: path to the executable
# e.g.
#   path = "/usr/bin/chromium"
path = "/usr/bin/weston-simple-egl"

# params: arguments of the excecutable
# e.g.
#   params = [
#     "--mus",
#     "--no-sandbox",
#     "--window-size=1080,1488",
#     "--ozone-platform=wayland",
#     "<URL>"
#   ]
